name: Weekly Team Sync
on:
  schedule:
    - cron: "*/5 * * * *" 

jobs:
 demo:
   runs-on: ubuntu-latest
   steps:
     - name: jaja
       run: |
         current_date_time=$(date)
         echo "Current date and time: $current_date_time"
   
          
